server.port=8081
spring.application.name=ignite-spring-boot-server-external-storage
spring.h2.console.enabled=true


spring.data.mongodb.uri=mongodb://sanzar:rahman@localhost:27017/admin
spring.jpa.hibernate.ddl-auto=create-drop
spring.main.allow-bean-definition-overriding=true